### ISSUE TITLE
enabling the dev tools causes crashes on pages with deferred loaders

### ISSUE THREAD

**Issue by ItamarShDev** [Code-Forge-Net/Remix-Dev-Tools#107]
```log
Warning: Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in your render function that asynchronously later calls tries to update the component. Move this work to useEffect instead.
    at JsonRenderer (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:19564:23)
    at div
    at InfoCard (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:19593:13)
    at div
    at div
    at li
    at RouteSegmentInfo (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:20157:27)
    at ol
    at div
    at PageTab (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:20234:18)
    at div
    at div
    at ContentPanel (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:25990:23)
    at div
    at div
    at MainPanel (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:17287:30)
    at div
    at DevTools (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:26371:28)
    at RDTContextProvider (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:16768:39)
    at RemixDevTools (http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:26417:24)
    at http://localhost:3000/build/_shared/dist-M3DBNZ4K.js:26493:20
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-ZLIKBL6J.js:3916:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-ZLIKBL6J.js:4563:9)
    at DataRoutes2 (http://localhost:3000/build/_shared/chunk-ZLIKBL6J.js:5209:5)
    at Router (http://localhost:3000/build/_shared/chunk-ZLIKBL6J.js:4341:15)
    at RouterProvider2 (http://localhost:3000/build/_shared/chunk-ZLIKBL6J.js:5026:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-ZLIKBL6J.js:7239:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-ZLIKBL6J.js:8101:46)
```

<img width="821" alt="image" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/953371/e4901bb1-c887-497e-ba0a-d8e2bc77848e">

**Comment by AlemTuzlak** [comment]
@ItamarShDev can you try with v4?

**Comment by ItamarShDev** [comment]
> @ItamarShDev can you try with v4?

Does this requies me to upgrade to Vite? i havent yet

**Comment by DennisKraaijeveld** [comment]
I have the same, using V4

**Comment by ItamarShDev** [comment]
works for me on latest version
