### ISSUE TITLE
Cannot start the dev server

### ISSUE THREAD

**Issue by marcob896** [Code-Forge-Net/Remix-Dev-Tools#112]
Hi, after upgrading to v4 I cannot start the dev server.

```
PS C:\Users\marco\git\marco-braglia-website> npm run dev

> dev
> node ./server.js

file:///C:/Users/marco/git/marco-braglia-website/node_modules/remix-development-tools/dist/index.js:86
        server.hot.on("all-route-info", (data, client) => {
                   ^

TypeError: Cannot read properties of undefined (reading 'on')
    at configureServer (file:///C:/Users/marco/git/marco-braglia-website/node_modules/remix-development-tools/dist/index.js:86:20)
    at _createServer (file:///C:/Users/marco/git/marco-braglia-website/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:60589:30)
    at async configResolved (C:\Users\marco\git\marco-braglia-website\node_modules\@remix-run\dev\dist\vite\plugin.js:746:27)
    at async Promise.all (index 2)
    at async resolveConfig (file:///C:/Users/marco/git/marco-braglia-website/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:68124:5)
    at async _createServer (file:///C:/Users/marco/git/marco-braglia-website/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:60327:20)
    at async file:///C:/Users/marco/git/marco-braglia-website/server.js:12:7

Node.js v20.11.0
```

this is my server.js at the moment:

```ts
import { createRequestHandler } from "@remix-run/express";
import { installGlobals } from "@remix-run/node";
import compression from "compression";
import express from "express";
import morgan from "morgan";

installGlobals();

const viteDevServer =
  process.env.NODE_ENV === "production"
    ? undefined
    : await import("vite").then((vite) =>
        vite.createServer({
          server: { middlewareMode: true },
        })
      );

const remixHandler = createRequestHandler({
  build: viteDevServer
    ? () => viteDevServer.ssrLoadModule("virtual:remix/server-build")
    : await import("./build/server/index.js"),
});

const app = express();

app.use(compression());

// http://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header
app.disable("x-powered-by");

// handle asset requests
if (viteDevServer) {
  app.use(viteDevServer.middlewares);
} else {
  // Vite fingerprints its assets so we can cache forever.
  app.use(
    "/assets",
    express.static("build/client/assets", { immutable: true, maxAge: "1y" })
  );
}

// Everything else (like favicon.ico) is cached for an hour. You may want to be
// more aggressive with this caching.
app.use(express.static("build/client", { maxAge: "1h" }));

app.use(morgan("tiny"));

// handle SSR requests
app.all("*", remixHandler);

const port = process.env.PORT || 3000;
app.listen(port, () =>
  console.log(`Express server listening at http://localhost:${port}`)
);
```

**Comment by AlemTuzlak** [comment]
@marcob896 is your vite version v5+?

**Comment by AlemTuzlak** [comment]
can you create a minimum repro, I'll take a look at what's going on!

**Comment by AlemTuzlak** [comment]
@marcob896 I just ran npm install on the upgrades branch and ran npm run dev and renamed 
```diff-ts
- import YoutubeVideo from "@/components/blog/YoutubeVideo";
+ import YoutubeVideo from "@/components/blog/youtubeVideo";
```

and started it without issues.

**Comment by AlemTuzlak** [comment]
It's not impacting, I just got that error when I ran your upgrades branch and after fixing it up everything work, it almost seems like some weird node_modules thing, can you try removing the whole node_modules folder and then running npm install?

**Comment by marcob896** [comment]
> It's not impacting, I just got that error when I ran your upgrades branch and after fixing it up everything worked, it almost seems like some weird node_modules thing, can you try removing the whole node_modules folder and then running npm install?

just did, same error. maybe trying to delete package-lock?

**Comment by marcob896** [comment]
ok. for the record, I had to remove both the node_modules folder AND the package-lock file, then run npm install. Now it starts, thanks for your support

**Comment by AlemTuzlak** [comment]
awesome, I'm glad we managed to sort it out! I'm closing it.
