### ISSUE TITLE
HMR Breaks with DevTools installed

### ISSUE THREAD

**Issue by kentcdodds** [Code-Forge-Net/Remix-Dev-Tools#25]
When I make a change in the Epic Stack and I get an HMR reload, I get the following error in the console:

<details>

<summary>The error</summary>

```
error-boundary.tsx:38 Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
    at throwException (react-dom.development.js:19055:35)
    at handleError (react-dom.development.js:26311:7)
    at renderRootSync (react-dom.development.js:26437:7)
    at performSyncWorkOnRoot (react-dom.development.js:26085:20)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at flushSync (react-dom.development.js:26201:7)
    at scheduleRefresh (react-dom.development.js:27795:5)
    at renderer.scheduleRefresh (renderer.js:584:1)
    at react-refresh-runtime.development.js:265:17
    at Set.forEach (<anonymous>) '\n    at GeneralErrorBoundary (http://localhost:3000/build/_shared/chunk-GHJAN7NM.js:42:3)\n    at body\n    at html\n    at Document (http://localhost:3000/build/root-XJYL7V5A.js?t=1690338998889:4736:3)\n    at ErrorBoundary (http://localhost:3000/build/root-XJYL7V5A.js?t=1690338998889:4928:17)\n    at RemixRouteError (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:8710:3)\n    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3640:9)\n    at DataRoutes (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3354:5)\n    at Router (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3433:15)\n    at RouterProvider (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3303:5)\n    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:8278:5)\n    at RemixBrowser (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:10443:40)'
overrideMethod @ console.js:213
GeneralErrorBoundary @ error-boundary.tsx:38
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
scheduleRefresh @ react-dom.development.js:27795
renderer.scheduleRefresh @ renderer.js:584
(anonymous) @ react-refresh-runtime.development.js:265
performReactRefresh @ react-refresh-runtime.development.js:254
(anonymous) @ browser.js:72
setTimeout (async)
(anonymous) @ browser.js:70
(anonymous) @ router.ts:977
updateState @ router.ts:977
completeNavigation @ router.ts:1058
startNavigation @ router.ts:1356
await in startNavigation (async)
revalidate @ router.ts:1206
(anonymous) @ browser.js:77
await in (anonymous) (async)
emit @ hmr-runtime:remix:hmr:64
ws.onmessage @ verify:73
Show 2 more frames
Show less
error-boundary.tsx:38 Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
    at throwException (react-dom.development.js:19055:35)
    at handleError (react-dom.development.js:26311:7)
    at renderRootSync (react-dom.development.js:26437:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (react-dom.development.js:26096:20)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at flushSync (react-dom.development.js:26201:7)
    at scheduleRefresh (react-dom.development.js:27795:5)
    at renderer.scheduleRefresh (renderer.js:584:1)
    at react-refresh-runtime.development.js:265:17 '\n    at GeneralErrorBoundary (http://localhost:3000/build/_shared/chunk-GHJAN7NM.js:42:3)\n    at body\n    at html\n    at Document (http://localhost:3000/build/root-XJYL7V5A.js?t=1690338998889:4736:3)\n    at ErrorBoundary (http://localhost:3000/build/root-XJYL7V5A.js?t=1690338998889:4928:17)\n    at RemixRouteError (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:8710:3)\n    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3640:9)\n    at DataRoutes (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3354:5)\n    at Router (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3433:15)\n    at RouterProvider (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3303:5)\n    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:8278:5)\n    at RemixBrowser (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:10443:40)'
overrideMethod @ console.js:213
GeneralErrorBoundary @ error-boundary.tsx:38
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
recoverFromConcurrentError @ react-dom.development.js:25850
performSyncWorkOnRoot @ react-dom.development.js:26096
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
scheduleRefresh @ react-dom.development.js:27795
renderer.scheduleRefresh @ renderer.js:584
(anonymous) @ react-refresh-runtime.development.js:265
performReactRefresh @ react-refresh-runtime.development.js:254
(anonymous) @ browser.js:72
setTimeout (async)
(anonymous) @ browser.js:70
(anonymous) @ router.ts:977
updateState @ router.ts:977
completeNavigation @ router.ts:1058
startNavigation @ router.ts:1356
await in startNavigation (async)
revalidate @ router.ts:1206
(anonymous) @ browser.js:77
await in (anonymous) (async)
emit @ hmr-runtime:remix:hmr:64
ws.onmessage @ verify:73
Show 2 more frames
Show less
react-dom.development.js:18687 The above error occurred in one of your React components:

    at Lazy
    at body
    at html
    at Document (http://localhost:3000/build/root-XJYL7V5A.js?t=1690338998889:4736:3)
    at App (http://localhost:3000/build/root-XJYL7V5A.js?t=1690338998889:4773:16)
    at SentryRoot
    at RemixRoute (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:8690:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3056:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3640:9)
    at DataRoutes (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3354:5)
    at Router (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3433:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3303:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:8278:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:10443:40)

React will try to recreate this component tree from scratch using the error boundary you provided, RenderErrorBoundary.
overrideMethod @ console.js:213
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
scheduleRefresh @ react-dom.development.js:27795
renderer.scheduleRefresh @ renderer.js:584
(anonymous) @ react-refresh-runtime.development.js:265
performReactRefresh @ react-refresh-runtime.development.js:254
(anonymous) @ browser.js:72
setTimeout (async)
(anonymous) @ browser.js:70
(anonymous) @ router.ts:977
updateState @ router.ts:977
completeNavigation @ router.ts:1058
startNavigation @ router.ts:1356
await in startNavigation (async)
revalidate @ router.ts:1206
(anonymous) @ browser.js:77
await in (anonymous) (async)
emit @ hmr-runtime:remix:hmr:64
ws.onmessage @ verify:73
Show 2 more frames
Show less
hooks.tsx:608 React Router caught the following error during render Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.
    at throwException (react-dom.development.js:19055:35)
    at handleError (react-dom.development.js:26311:7)
    at renderRootSync (react-dom.development.js:26437:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (react-dom.development.js:26096:20)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at flushSync (react-dom.development.js:26201:7)
    at scheduleRefresh (react-dom.development.js:27795:5)
    at renderer.scheduleRefresh (renderer.js:584:1)
    at react-refresh-runtime.development.js:265:17 {componentStack: '\n    at Lazy\n    at body\n    at html\n    at Docume…st:3000/build/_shared/chunk-DJH6CC34.js:10443:40)'} 
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3640:9)
    at DataRoutes (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3354:5)
    at Router (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3433:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:3303:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:8278:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-DJH6CC34.js:10443:40)
```

</details>

I haven't spent any time debugging this, but if I remove the dev tools then the issue goes away.

**Comment by AlemTuzlak** [comment]
@kentcdodds man that's a scary one, any idea on what tab you were on when this happened? I have an idea when it might've happened just need to check

**Comment by kentcdodds** [comment]
It happens when I'm not even using the dev tools.

**Comment by fredericoo** [comment]
`1.1.1` works fine, `1.3.0` breaks for me. Any route changes also unmount and mount the whole app again. It does not happen in `1.1.1` so im staying there despite missing out on the route boundaries :(

**Comment by AlemTuzlak** [comment]
@fredericoo try wrapping the app in suspense, refer to the troubleshooting section of readme, I'm trying to figure the exact cause

**Comment by AlemTuzlak** [comment]
@fredericoo try wrapping the app in suspense, refer to the troubleshooting section of readme, I'm trying to figure the exact cause

**Comment by AlemTuzlak** [comment]
@kentcdodds @fredericoo Sorry I am just a tool, the setup uses lazy, which requires you to have a suspense over it which in turn causes this issue

**Comment by fredericoo** [comment]
> @fredericoo does this happen with the flag turned on or off? The remount

just updating to 1.3 causes it immediately, without any config changes. I have the dev tools wrapped in suspense but not the whole app. I’ll remain on 1.1.1 while this is sorted out and documented, it's still pretty good!
